import json
import logging
from .base_client import BaseAIClient
from .models import AIRequest, AIResponse

logger = logging.getLogger(__name__)

# Template satu soal
SINGLE_QUESTION = {
    "question": "This is a mock question.",
    "type": "multiple_choice",
    "choices": [
        {"label": "A", "text": "Option A"},
        {"label": "B", "text": "Option B"},
        {"label": "C", "text": "Option C"},
        {"label": "D", "text": "Option D"},
    ],
    "answer": "A",
    "explanation": "This answer is generated by Mock AI.",
}

class MockClient(BaseAIClient):
    def __init__(self):
        self._initialized = False
        self._model_name = "mock-model"

    async def initialize(self) -> None:
        self._initialized = True
        logger.info("Mock provider initialized.")

    async def generate(self, request: AIRequest) -> AIResponse:
        logger.info("Mock request started.")
        count = request.metadata.get("number_of_questions", 1)
        questions = []
        for i in range(count):
            q = dict(SINGLE_QUESTION)
            q["question"] = f"This is mock question #{i + 1}."
            questions.append(q)

        response_data = {"questions": questions}
        response_text = json.dumps(response_data, indent=2)
        logger.info(f"Mock generated {count} question(s).")
        return AIResponse(
            response_text=response_text,
            provider="mock",
            metadata={
                "model": self._model_name,
                "finish_reason": "stop",
                "usage": {
                    "prompt_tokens": 0,
                    "completion_tokens": len(response_text.split()),
                    "total_tokens": len(response_text.split()),
                },
            },
        )

    async def health_check(self) -> bool:
        return self._initialized

    async def close(self) -> None:
        self._initialized = False